export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  users: {
    root: '/users',
    byId: (id) => `/users/${id}`,
    assignments: (id) => `/users/${id}/assignments`,
    deactivate: (id) => `/users/${id}/deactivate`,
    activate: (id) => `/users/${id}/activate`,
    reassign: (id) => `/users/${id}/reassign`,
  },
  roles: {
    root: '/roles',
    permissions: '/roles/permissions',
    setPermissions: (id) => `/roles/${id}/permissions`,
  },
  sop: {
    root: '/sop',
    byId: (id) => `/sop/${id}`,
    version: (id) => `/sop/versions/${id}`,
    stages: (id) => `/sop/${id}/stages`,
    stage: (id, stageId) => `/sop/${id}/stages/${stageId}`,
    reorder: (id) => `/sop/${id}/stages/reorder`,
    publish: (id) => `/sop/${id}/publish`,
  },
  projects: {
    root: '/projects',
    summary: '/projects/summary',
    preview: (sopTemplateId) => `/projects/preview-stages?sopTemplateId=${sopTemplateId}`,
    byId: (id) => `/projects/${id}`,
    members: (id) => `/projects/${id}/members`,
    stages: (id) => `/projects/${id}/stages`,
    stageStatus: (id, stageId) => `/projects/${id}/stages/${stageId}/status`,
    stageAssign: (id, stageId) => `/projects/${id}/stages/${stageId}/assign`,
    stageHistory: (id, stageId) => `/projects/${id}/stages/${stageId}/status-history`,
    stageDocuments: (id, stageId) => `/projects/${id}/stages/${stageId}/documents`,
    stageDetail: (id, stageId) => `/projects/${id}/stages/${stageId}`,
    stageSignoff: (id, stageId) => `/projects/${id}/stages/${stageId}/signoff`,
    stagePermissions: (id, stageId) => `/projects/${id}/stages/${stageId}/permissions`,
    stageBugs: (id, stageId) => `/projects/${id}/stages/${stageId}/bugs`,
    bugs: (id) => `/projects/${id}/bugs`,
    bug: (id, bugId) => `/projects/${id}/bugs/${bugId}`,
    bugStatus: (id, bugId) => `/projects/${id}/bugs/${bugId}/status`,
  },
  audit: {
    root: '/audit',
    filters: '/audit/filters',
  },
  me: {
    assignments: '/me/assignments',
  },
  notifications: {
    root: '/notifications',
    read: (id) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
  },
  settings: {
    me: '/settings/me',
    system: '/settings/system',
  },
  reports: { root: '/reports' },
  search: { root: (q) => `/search?q=${encodeURIComponent(q)}` },
  rolePreview: (id) => `/roles/${id}/preview`,
  public: { track: (brd) => `/public/track?brd=${encodeURIComponent(brd)}` },
};
